TRACER_ENV_VAR = "MUTATE_CSHARP_TRACER_FILEPATH"
FUZZ_D_GENERATED_FILENAME = "main"
LONG_LOWER_BOUND = -(1 << 63)
LONG_UPPER_BOUND = (1 << 63) - 1
COMPILATION_TIMEOUT_SCALE_FACTOR = 3
EXECUTION_TIMEOUT_SCALE_FACTOR = 3

# Ensure consistency with C#.
INVALID_FILE_NAME_CHARACTERS = ['\0', '/']
