from enum import Enum

class RegularProgramStatus(Enum):
    COMPILER_TIMEOUT = 1
    COMPILER_EXITCODE_NON_ZERO = 2
    RUNTIME_TIMEOUT = 3
    RUNTIME_EXITCODE_NON_ZERO = 4
    RUNTIME_EXITCODE_DIFFER = 5
    RUNTIME_STDOUT_DIFFER = 6
    RUNTIME_STDERR_DIFFER = 7
    EXPECTED_SUCCESS = 8
    KNOWN_BUG = 9

class MutantStatus(Enum):
    KILLED_COMPILER_CRASHED = 1
    KILLED_COMPILER_TIMEOUT = 2
    KILLED_COMPILER_MISSING_EXECUTABLE_OUTPUT = 3
    KILLED_RUNTIME_TIMEOUT = 4
    KILLED_RUNTIME_EXITCODE_DIFFER = 5
    KILLED_RUNTIME_STDOUT_DIFFER = 6
    KILLED_RUNTIME_STDERR_DIFFER = 7
    SURVIVED = 8
    # SURVIVED_HASH_EQUIVALENT = 8
    # SURVIVED_HASH_DIFFER = 9
    # SURVIVED_INTERNAL = 10
